services:
  db:
    container_name: ${DB_NAME}
    image: postgres:17.0-alpine3.20
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./cerebroVolume :/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  
  customerService:
    depends_on:
      - db
    container_name: ${CUSTOMER_SERVICE_NAME}
    image: chamito/customer-service:1.1.1
    ports:
      - "${CUSTOMER_SERVICE_PORT}:${CUSTOMER_SERVICE_PORT}"
    environment:
      # Customer Service
      - APP_PORT=${CUSTOMER_SERVICE_PORT}
      - APP_HOST=${CUSTOMER_SERVICE_HOST}
      # Database Configuration
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  
  cerebro:
    container_name: ${CEREBRO_NAME}
    depends_on:
      - customerService
    image: chamito/cerebro:1.1.1
    ports:
      - "${CEREBRO_PORT}:${CEREBRO_PORT}"
    environment:
      # Cerebro Configuration
      - CEREBRO_PORT=${CEREBRO_PORT}
      - CEREBRO_HOST=${CEREBRO_HOST}
      - JWT_SECRET=${JWT_SECRET}
      # Customer Service
      - CUSTOMER_SERVICE_PORT=${CUSTOMER_SERVICE_PORT}
      - CUSTOMER_SERVICE_HOST=customerService